### ISSUE TITLE
Add CMIF Method Implementation

### ISSUE THREAD

**Issue by nitesh31mishra** [SEEDGuard/SEEDConsistencyChecker#11]
**Tasks**

- [ ] Implement the CMIF Method - paper CMIF: [When to Say What: Learning to Find Condition-Message Inconsistencies](https://ieeexplore.ieee.org/abstract/document/10172811)
- [ ] Add sample input data in test folder for your method.
- [ ] Provide testing script in `test/method` folder which runs with the above sample data.
- [ ] Add Dockerfile for your method.
- [ ] Method Integrated Completely - Running State.

**Note:**

- Don't forget to reference this issue number in your commits and PRs (by mentioning the issue number everything will be linked to thos issue as task). e.g. for a commit `add method implementation #111`.
- Also feel free to drop a comment over here by mentioning what is the current state after that commit or what you are working on next.
- Drop your questions or problem you are stuck at during implementation.
- Reference main branch for any file strcuture information.

**Comment by maxxbw54** [comment]
@nitesh31mishra  can u update @EZ7051  progresss?
