### ISSUE TITLE
Add Deep_justintime Method Implementation 

### ISSUE THREAD

**Issue by nitesh31mishra** [SEEDGuard/SEEDConsistencyChecker#12]
**Tasks**

- [x] Implement the Deep_justintime Method - paper Deep_justintime : [Deep Just-In-Time Inconsistency Detection Between Comments and Source Code](https://arxiv.org/pdf/2010.01625.pdf)
- [x] Add sample input data in test folder for your method.
- [x] Provide testing script in `test/method` folder which runs with the above sample data.
- [x] Add Dockerfile for your method. (ETA: 19 April)
- [x] Method Integrated Completely - Running State.
- [ ] Get the approval on this implemented method from original authors of the paper. 

**Note:**

- Don't forget to reference this issue number in your commits and PRs (by mentioning the issue number everything will be linked to thos issue as task). e.g. for a commit `add method implementation #111`.
- Also feel free to drop a comment over here by mentioning what is the current state after that commit or what you are working on next.
- Drop your questions or problem you are stuck at during implementation.
- Reference main branch for any file strcuture information.

**Comment by maxxbw54** [comment]
@vignes-12  would u pls update ur progress here?

**Comment by nitesh31mishra** [comment]
Hey @vignes-12 , could you push the latest code changes and the sample input, output file.
Thanks!
