### ISSUE TITLE
Add DeepName Method Implementation

### ISSUE THREAD

**Issue by nitesh31mishra** [SEEDGuard/SEEDConsistencyChecker#15]
**Tasks**

- [ ] Implement the DeepName Method - paper: [A Context-based Automated Approach for Method Name Consistency Checking and Suggestion](https://doi.org/10.1109/ICSE43902.2021.00060), [Replication Package](https://github.com/deepname2021icse/DeepName-2021-ICSE)
- [ ] Add sample input data in test folder for your method.
- [ ] Provide testing script in `test/method` folder which runs with the above sample data.
- [ ] Add Dockerfile for your method.
- [ ] Method Integrated Completely - Running State.
- [ ] Get the approval on this implemented method from original authors of the paper. 

**Note:**

- Don't forget to reference this issue number in your commits and PRs (by mentioning the issue number everything will be linked to thos issue as task). e.g. for a commit `add method implementation #111`.
- Also feel free to drop a comment over here by mentioning what is the current state after that commit or what you are working on next.
- Drop your questions or problem you are stuck at during implementation.
- Reference main branch for any file strcuture information.
