### ISSUE TITLE
Add code-comment-inconsistencies Method Implementation

### ISSUE THREAD

**Issue by nitesh31mishra** [SEEDGuard/SEEDConsistencyChecker#16]
**Tasks**

- [ ] Implement the code-comment-inconsistencies Method - paper: [A Large-Scale Empirical Study on Code-Comment Inconsistencies](https://doi.org/10.1109/ICPC.2019.00019), [Replication Package](https://github.com/USI-INF-Software/ICPC2019-code-comment-inconsistencies)
- [ ] Add sample input data in test folder for your method.
- [ ] Provide testing script in `test/method` folder which runs with the above sample data.
- [ ] Add Dockerfile for your method.
- [ ] Method Integrated Completely - Running State.
- [ ] Get the approval on this implemented method from original authors of the paper. 

**Note:**

- Don't forget to reference this issue number in your commits and PRs (by mentioning the issue number everything will be linked to thos issue as task). e.g. for a commit `add method implementation #111`.
- Also feel free to drop a comment over here by mentioning what is the current state after that commit or what you are working on next.
- Drop your questions or problem you are stuck at during implementation.
- Reference main branch for any file strcuture information.

**Comment by JaytheDragon** [comment]
Started working on it
