### ISSUE TITLE
Add MCCL Method Implementation

### ISSUE THREAD

**Issue by nitesh31mishra** [SEEDGuard/SEEDConsistencyChecker#9]
**Tasks**

- [ ] Implement the MCCL Method - paper MCCL: [Code Comment Inconsistency Detection Based on Confidence Learning](https://ieeexplore.ieee.org/abstract/document/10416264) 
- [ ] Add sample input data in test folder for your method.
- [ ] Provide testing script in `test/method` folder which runs with the above sample data.
- [ ] Add Dockerfile for your method.
- [ ] Method Integrated Completely - Running State.

**Note:**

- Don't forget to reference this issue number in your commits and PRs (by mentioning the issue number everything will be linked to thos issue as task). e.g. for a commit `add method implementation #111`.
- Also feel free to drop a comment over here by mentioning what is the current state after that commit or what you are working on next.
- Drop your questions or problem you are stuck at during implementation.
- Reference main branch for any file strcuture information.
